Change to use Uri in order to meet Q's requirement (supporting MediaStore)
iamutkarshtiwari/Ananas pull request #78
Opened 2020-12-22 08:00 UTC by KuanWeiTW

2020-12-22 08:00 UTC, KuanWeiTW commented
Also update gradle as well.

2021-01-02 08:08 UTC, iamutkarshtiwari requested changes

2021-01-02 08:08 UTC, iamutkarshtiwari commented on ananas/src/main/java/kuanweitw/github/io/ananas/editimage/fragment/TextEditorDialogFragment.java
> +import kuanweitw.github.io.ananas.R;
There seem to be unintended package changes. Could you please revert these?

2021-01-30 13:22 UTC, iamutkarshtiwari commented
Closing it for now due to inactivity. Please feel free to re-open. Thanks!

2021-01-30 13:22 UTC, closed without merging